#!/usr/bin/env python3
"""Development v0.5.3: multi-scale pure Behavior Window minimality search.

Motivation from the frozen-witness v0.5 fixed-span diagnostic:
- compact behavior regions can require a small span,
- broad/multi-branch behavior regions can require a larger span,
- a single global span therefore creates a scale conflict.

This experiment changes only evidence realization. Retrieval, frozen witnesses,
query terms, scoring hard gates, greedy objective coefficients, and the winner
ordering remain unchanged. Candidate windows from a small predeclared family of
spans compete in one common greedy pool; complete fixed-span cards are never
unioned.

Development only. Do not use this result as unseen generalization evidence.
"""
from __future__ import annotations

import json
import statistics
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import search_repo_behavior_witness_minimality_v05 as fixed  # noqa: E402

behavior = fixed.behavior_v03

# Declared before this controller is executed. Families deliberately cover
# compact, medium, and broad behavior without introducing task-specific spans.
SPAN_FAMILIES = (
    (4, 8),
    (6, 12),
    (8, 16),
    (8, 24),
    (6, 12, 24),
    (8, 16, 24),
    (4, 8, 16, 24),
)
MAX_WINDOWS = (2, 3, 4, 5, 6)
MERGE_GAPS = (0, 1, 2)


@dataclass(frozen=True)
class MultiScaleCfg:
    spans: tuple[int, ...]
    max_windows: int
    merge_gap: int


_source_cache: dict[tuple, tuple[list[str], list[dict[int, float]]]] = {}
_candidate_cache: dict[tuple[int, tuple[int, ...]], list[dict]] = {}


def source_state(repo: Path, row: dict, terms: list[tuple[str, float, bool]]):
    key = (str(repo), row["path"], tuple(terms))
    state = _source_cache.get(key)
    if state is None:
        lines = (repo / row["path"]).read_text(encoding="utf-8", errors="replace").splitlines()
        supports = behavior.per_line_support(lines, terms)
        state = (lines, supports)
        _source_cache[key] = state
    return state


def candidate_features(
    lines: list[str], supports: list[dict[int, float]], spans: tuple[int, ...]
) -> list[dict]:
    key = (id(lines), spans)
    cached = _candidate_cache.get(key)
    if cached is not None:
        return cached

    # Deduplicate identical intervals across scales. If an interval can be
    # generated by more than one span, its content-derived features are equal;
    # retain the smallest originating span only as provenance.
    by_interval: dict[tuple[int, int], dict] = {}
    for span in spans:
        for start, end in behavior.candidate_windows(lines, supports, span):
            per_term, structural, density, byte_cost = behavior.window_features(
                lines, supports, start, end
            )
            if not per_term:
                continue
            interval = (start, end)
            row = {
                "start": start,
                "end": end,
                "span": span,
                "per_term": per_term,
                "structural": structural,
                "density": density,
                "bytes": byte_cost,
            }
            old = by_interval.get(interval)
            if old is None or span < old["span"]:
                by_interval[interval] = row
    out = sorted(by_interval.values(), key=lambda r: (r["start"], r["end"], r["span"]))
    _candidate_cache[key] = out
    return out


def choose_windows(
    lines: list[str], supports: list[dict[int, float]], cfg: MultiScaleCfg
) -> list[tuple[int, int]]:
    remaining = list(candidate_features(lines, supports, cfg.spans))
    selected: list[dict] = []
    covered: set[int] = set()

    while remaining and len(selected) < cfg.max_windows:
        best = None
        best_key = None
        for window in remaining:
            new_gain = sum(v for i, v in window["per_term"].items() if i not in covered)
            repeat_gain = sum(v for i, v in window["per_term"].items() if i in covered)
            # Exactly the v0.3/v0.5 objective; no new fitted coefficient.
            objective = (
                new_gain
                + 0.10 * repeat_gain
                + 0.30 * window["structural"]
                + 0.20 * window["density"]
                - 0.00008 * window["bytes"]
            )
            key = (
                objective,
                new_gain,
                window["structural"],
                -window["bytes"],
                -window["start"],
            )
            if best_key is None or key > best_key:
                best_key = key
                best = window
        if best is None or best_key is None or best_key[0] <= 0:
            break
        selected.append(best)
        covered.update(best["per_term"])
        remaining = [
            window
            for window in remaining
            if not (
                window["start"] <= best["end"] + cfg.merge_gap
                and best["start"] <= window["end"] + cfg.merge_gap
            )
        ]

    intervals = sorted((w["start"], w["end"]) for w in selected)
    merged: list[list[int]] = []
    for start, end in intervals:
        if not merged or start > merged[-1][1] + cfg.merge_gap:
            merged.append([start, end])
        else:
            merged[-1][1] = max(merged[-1][1], end)
    return [(start, end) for start, end in merged]


def behavior_card(repo: Path, row: dict, terms, cfg: MultiScaleCfg) -> dict:
    lines, supports = source_state(repo, row, terms)
    windows = choose_windows(lines, supports, cfg)
    records = []
    for window_id, (start, end) in enumerate(windows, 1):
        for line_no in range(start, end + 1):
            records.append({"window": window_id, "line": line_no, "text": lines[line_no - 1]})
    return {"path": row["path"], "windows": windows, "records": records}


def evaluate_policy(cached: list[dict], cfg: MultiScaleCfg) -> dict:
    task_rows: list[dict] = []
    false_direct = 0
    for item in cached:
        task = item["task"]
        expected_file = task["expected_file"]
        frontier_paths = [row["path"] for row in item["frontier"]]
        frontier_hit = expected_file in frontier_paths
        if item["proof_path"] is not None and item["proof_path"] != expected_file:
            false_direct += 1

        cards = [behavior_card(item["repo"], row, item["terms"], cfg) for row in item["frontier"]]
        visible = fixed.visible_line_identities(cards)
        witness_hit, witness_rows = fixed.witness_score(task, visible)
        unique_lines = len(visible)
        emitted_windows = sum(len(card["windows"]) for card in cards)
        per_card_max_windows = max((len(card["windows"]) for card in cards), default=0)
        task_rows.append(
            {
                "task_id": task["task_id"],
                "frontier_hit": frontier_hit,
                "witness_hit": witness_hit,
                "witness_rows": witness_rows,
                "unique_source_lines": unique_lines,
                "emitted_windows": emitted_windows,
                "max_windows_in_single_card": per_card_max_windows,
                "frontier": frontier_paths,
                "proof_path": item["proof_path"],
            }
        )

    unique_lines = [row["unique_source_lines"] for row in task_rows]
    emitted_windows = [row["emitted_windows"] for row in task_rows]
    frontier_hits = sum(row["frontier_hit"] for row in task_rows)
    witness_hits = sum(row["witness_hit"] for row in task_rows)
    hard_gate = frontier_hits == len(task_rows) and witness_hits == len(task_rows) and false_direct == 0
    return {
        "cfg": {
            "spans": list(cfg.spans),
            "max_windows": cfg.max_windows,
            "merge_gap": cfg.merge_gap,
        },
        "hard_gate": hard_gate,
        "frontier_hits": frontier_hits,
        "witness_hits": witness_hits,
        "false_direct": false_direct,
        "worst_case_unique_source_lines": max(unique_lines),
        "mean_unique_source_lines": statistics.fmean(unique_lines),
        "actual_max_windows_emitted_per_task": max(emitted_windows),
        "mean_windows_emitted_per_task": statistics.fmean(emitted_windows),
        "task_rows": task_rows,
    }


def winner_key(row: dict) -> tuple:
    cfg = row["cfg"]
    # Preserve the pre-fixed cost order. For the new scale-family dimension,
    # prefer fewer configured spans only after all original cost dimensions.
    return (
        row["worst_case_unique_source_lines"],
        row["mean_unique_source_lines"],
        row["actual_max_windows_emitted_per_task"],
        cfg["max_windows"],
        max(cfg["spans"]),
        cfg["merge_gap"],
        len(cfg["spans"]),
        tuple(cfg["spans"]),
    )


def compact(row: dict) -> dict:
    return {k: v for k, v in row.items() if k != "task_rows"}


def failures(row: dict) -> list[dict]:
    out = []
    for task_row in row["task_rows"]:
        if task_row["frontier_hit"] and task_row["witness_hit"]:
            continue
        out.append(
            {
                "task_id": task_row["task_id"],
                "frontier_hit": task_row["frontier_hit"],
                "witness_hit": task_row["witness_hit"],
                "witness_rows": [w for w in task_row["witness_rows"] if not w["hit"]],
            }
        )
    return out


def main() -> None:
    manifest = fixed.load_manifest()
    cached = fixed.build_cache(manifest)
    configs = [
        MultiScaleCfg(tuple(spans), max_windows, gap)
        for spans in SPAN_FAMILIES
        for max_windows in MAX_WINDOWS
        for gap in MERGE_GAPS
    ]
    rows = [evaluate_policy(cached, cfg) for cfg in configs]
    eligible = sorted((row for row in rows if row["hard_gate"]), key=winner_key)
    selected = eligible[0] if eligible else None
    near = sorted(rows, key=lambda r: (-r["witness_hits"], winner_key(r)))[:12]

    out = {
        "experiment": "repo-behavior-witness-multiscale-development-v0.5.3",
        "status": "development_only_same_frozen_witness_multiscale_search",
        "witness_manifest": str(fixed.WITNESS_MANIFEST.relative_to(ROOT)).replace("\\", "/"),
        "tasks": len(cached),
        "candidate_policies": len(rows),
        "grid": {
            "span_families": [list(x) for x in SPAN_FAMILIES],
            "max_windows": list(MAX_WINDOWS),
            "merge_gaps": list(MERGE_GAPS),
        },
        "retrieval_policy": {"exact_quota": fixed.EXACT_QUOTA, "frontier_top_k": fixed.TOP_K},
        "algorithm_change": "candidate windows from multiple generic spans compete in one greedy pool; objective coefficients unchanged; no fixed-policy union and no hybrid evidence",
        "hard_gate": "frontier 14/14 + every frozen witness region passes + false_direct 0",
        "winner_rule": [
            "min worst_case_unique_source_lines",
            "min mean_unique_source_lines",
            "min actual_max_windows_emitted_per_task",
            "min configured max_windows",
            "min max configured span",
            "min merge_gap",
            "then fewer/narrower span families only as deterministic tie-breakers",
        ],
        "eligible_policies": len(eligible),
        "selected": compact(selected) if selected is not None else None,
        "selected_task_rows": selected["task_rows"] if selected is not None else [],
        "top_eligible": [compact(row) for row in eligible[:12]],
        "nearest_policies": [{**compact(row), "failures": failures(row)} for row in near],
        "all_policy_metrics": [compact(row) for row in rows],
        "claim_boundary": "Same already-observed development repositories and same source-audited frozen witnesses. Fresh sealed repositories remain unopened.",
    }
    print(json.dumps(out, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
